//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicar_Balonmano.LINQ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class balonmanoEntities : DbContext
    {
        public balonmanoEntities()
            : base("name=balonmanoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EQUIPOS> EQUIPOS { get; set; }
        public virtual DbSet<GOLES_PARTIDO> GOLES_PARTIDO { get; set; }
        public virtual DbSet<JUGADORES> JUGADORES { get; set; }
        public virtual DbSet<PARTIDOS> PARTIDOS { get; set; }
    }
}
