//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicar_Balonmano.LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JUGADORES()
        {
            this.GOLES_PARTIDO = new HashSet<GOLES_PARTIDO>();
        }
    
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public byte[] Foto { get; set; }
        public string Telefono { get; set; }
        public int Equipo { get; set; }
    
        public virtual EQUIPOS EQUIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOLES_PARTIDO> GOLES_PARTIDO { get; set; }
    }
}
