//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicar_Balonmano.LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTIDOS()
        {
            this.GOLES_PARTIDO = new HashSet<GOLES_PARTIDO>();
        }
    
        public int Id_partido { get; set; }
        public int Equipo_local { get; set; }
        public int Equipo_visitante { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Goles_local { get; set; }
        public int Goles_visitante { get; set; }
        public Nullable<int> Equipo_ganador { get; set; }
    
        public virtual EQUIPOS EQUIPOS { get; set; }
        public virtual EQUIPOS EQUIPOS1 { get; set; }
        public virtual EQUIPOS EQUIPOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOLES_PARTIDO> GOLES_PARTIDO { get; set; }
    }
}
